Repository AthennaIO/Config, pull requests merged in 2023-01, with the labels that each got.

#31 Better versioning
  package-lock.json
  package.json
  src/Env/Env.js
  src/Helpers/EnvHelper.js
  src/index.d.ts
Labels: feature

#33 fix(config): dont use safe load as default in loadAll
  package.json
  src/index.d.ts
  src/index.js
Labels: fix

#35 fix(config): replace one and double quotes
  package-lock.json
  package.json
  src/index.d.ts
  src/index.js
  tests/Stubs/config/database.js
  tests/Unit/ConfigTest.js
Labels: fix

#37 chore(npm): update dependencies
  package-lock.json
  package.json
Labels: chore

#38 Add Windows support and refactor project to TypeScript
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  bin/japaTypes.ts
  bin/test.ts
  package-lock.json
  package.json
  src/Config/Config.ts
  src/Env/Env.ts
  src/Exceptions/ConfigNotNormalizedException.js
  src/Exceptions/ConfigSyntaxException.ts
  src/Exceptions/RecursiveConfigException.js
  src/Exceptions/RecursiveConfigException.ts
  src/Globals/Config.ts
  src/Globals/Env.ts
  src/Helpers/EnvHelper.ts
  src/index.d.ts
  src/index.js
  src/index.ts
  tests/Stubs/.env.path
  tests/Stubs/config/app.ts
  tests/Stubs/config/database.ts
  tests/Stubs/config/notNormalized.ts
  tests/Stubs/config/recursiveOne.ts
  tests/Stubs/config/recursiveTwo.ts
  tests/Stubs/syntaxError.ts.template
  tests/Unit/ConfigTest.ts
  tests/Unit/EnvTest.ts
  tsconfig.json
Labels: build, refactor, styles, test, semver-minor

#39 Migrate project to TS
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  bin/japaTypes.ts
  bin/test.ts
  package-lock.json
  package.json
  src/Config/Config.ts
  src/Env/Env.ts
  src/Exceptions/ConfigNotNormalizedException.js
  src/Exceptions/ConfigSyntaxException.ts
  src/Exceptions/RecursiveConfigException.js
  src/Exceptions/RecursiveConfigException.ts
  src/Globals/Config.ts
  src/Globals/Env.ts
  src/Helpers/EnvHelper.ts
  src/index.d.ts
  src/index.js
  src/index.ts
  tests/Stubs/.env.path
  tests/Stubs/config/app.ts
  tests/Stubs/config/database.ts
  tests/Stubs/config/notNormalized.ts
  tests/Stubs/config/recursiveOne.ts
  tests/Stubs/config/recursiveTwo.ts
  tests/Stubs/syntaxError.ts.template
  tests/Unit/ConfigTest.ts
  tests/Unit/EnvTest.ts
  tsconfig.json
Labels: feature, styles, semver-minor

#40 fix(cd): use node version 14
  .github/workflows/cd.yml
Labels: cd, fix
